
export enum PatternType {
  CONCENTRIC_DIAMONDS = 'CONCENTRIC_DIAMONDS',
  CORNER_DIAMONDS = 'CORNER_DIAMONDS',
  DIAMOND_PARQUET = 'DIAMOND_PARQUET',
  DIAGONAL_STRIPES = 'DIAGONAL_STRIPES',
  SYMMETRIC_CROSS = 'SYMMETRIC_CROSS',
  SPIRAL = 'SPIRAL',
  HEART = 'HEART',
  RANDOM = 'RANDOM',
}

export enum PaletteName {
  RAINBOW = 'RAINBOW',
  GRAYSCALE = 'GRAYSCALE',
  SUNSET = 'SUNSET',
  FOREST = 'FOREST',
}

export interface Cell {
  x: number;
  y: number;
  color: string;
}
